# Generated by Django 5.1.7 on 2025-09-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('yolo', 'YOLO - Object Detection'), ('ocr', 'OCR - Text Recognition'), ('transformer', 'Transformer - NLP')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('weights_file', models.FileField(blank=True, null=True, upload_to='detection_models/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detection Model',
                'verbose_name_plural': 'Detection Models',
            },
        ),
        migrations.CreateModel(
            name='DetectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_jobs', to='documents.document')),
                ('models_used', models.ManyToManyField(related_name='jobs', to='detection.detectionmodel')),
            ],
            options={
                'verbose_name': 'Detection Job',
                'verbose_name_plural': 'Detection Jobs',
                'ordering': ['-started_at'],
            },
        ),
    ]
